# Generated by Django 3.2.15 on 2025-09-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_application_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='what_role_in_team_setting',
        ),
        migrations.AddField(
            model_name='application',
            name='fun_question',
            field=models.TextField(default='', help_text='If you were stranded on a deserted island with just a computer, a power outlet and your best friend, what program would you build?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='application',
            name='what_past_experience',
            field=models.TextField(help_text='Describe the most significant challenges you faced in a project/hackathon. What did you learn from them?', max_length=1000),
        ),
    ]
