# Generated by Django 3.2.15 on 2025-09-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20250923_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='conduct_agree',
            field=models.BooleanField(default=False, help_text='I have read and agree to the <a href="https://github.com/MLH/mlh-policies/blob/main/code-of-conduct.md" rel="noopener noreferrer" target="_blank">MLH code of conduct</a>.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='fun_question',
            field=models.TextField(default='', help_text='If you were stranded on a deserted island with just a computer and your best friend, what program would you build?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='application',
            name='logistics_agree',
            field=models.BooleanField(default=False, help_text='I authorize you to share my application/registration information with Major League Hacking for event administration, ranking, and MLH administration in-line with the <a href="https://github.com/MLH/mlh-policies/blob/main/privacy-policy.md" rel="noopener noreferrer" target="_blank">MLH Privacy Policy</a>. I further agree to the terms of both the <a href="https://github.com/MLH/mlh-policies/blob/main/contest-terms.md" rel="noopener noreferrer" target="_blank">MLH Contest Terms and Conditions</a> and the <a href="https://github.com/MLH/mlh-policies/blob/main/privacy-policy.md" rel="noopener noreferrer" target="_blank">MLH Privacy Policy.</a>'),
        ),
    ]
