# Generated by Django 3.2.15 on 2025-10-09 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20250923_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d[\\d\\s()-]{7,}$', message='Enter a valid phone number.')]),
        ),
    ]
